language: go

go:
  - 1.12.x
  - 1.13.x

before_install:
  - go get github.com/gorilla/websocket
  - go get github.com/mattn/goveralls

script:
  - go test ./server -cover
  - go test ./client -cover
  - $GOPATH/bin/goveralls -service=travis-ci

